### PR TITLE
Temp fix #68

### LINKED ISSUE #68: Instant crash
If I build from source it crashes.
Ex: Unhandled exception at 0x06217CE8 (Windows.UI.Xaml.dll) in BreadPlayer.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x157DCCE8, 0x00000006). occurred
Ex2: An exception of type 'System.Exception' occurred in System.Private.CoreLib.dll but was not handled in user code
Unspecified error (Excep_FromHResult 0x80004005) occurred

### PR DESCRIPTION
**Pull request by Bond-009**
A temp fix for issue #68

### CODE REVIEW

**Comment by theweavrs** [comment]
@Bond-009 Any updates on the issue?

**Comment by Bond-009** [comment]
Yes, I tried again and now it crashes at this line:
devenv_2016-12-17_22-35-26

**Comment by Bond-009** [comment]
System.Exception occurred
  HResult=0x80004005
  Message=Unspecified error (Excep_FromHResult 0x80004005)
  Source=<unknown>
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BreadPlayer.ViewModels.SettingsViewModel.<AutoLoadMusicLibrary>d__57.MoveNext() in D:\Bond\Programming\Github\BreadPlayer\BreadPlayer.Core\ViewModels\SettingsViewModel.cs:line 214
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 113
   at BreadPlayer.ViewModels.SettingsViewModel.<HandleMessage>d__37.MoveNext() in D:\Bond\Programming\Github\BreadPlayer\BreadPlayer.Core\ViewModels\SettingsViewModel.cs:line 123

**Comment by theweavrs** [comment]
@Bond-009 Of course it does, that's basically the same place where it was crashing before. Set breakpoints inside the `AddFolderToLibraryAsync` method as you did before especially on `debugFiles` variable I added in the latest commit. Now, in the `Locals` check its value. Is it null?

We can't add try/catch just now because that won't solve the problem just prevent the crash. We need to load the songs into the player, so let's figure this out and afterwards we will have to take precautionary measures and add try/catch.

**Comment by Bond-009** [comment]
It never reaches `AddFolderToLibraryAsync` in my latest test so ... yeah
(This issue drives me crazy)

**Comment by theweavrs** [comment]
@Bond-009 Oh, sorry. You will have to remove the `if` statement to reach `AddFolderToLibraryAsync`.

**Comment by Bond-009** [comment]
Count fails

**Comment by theweavrs** [comment]
@Bond-009 I see. This is still vague, we now know at least that `Count` fails but not why it fails. Try turning on `Compile With .NET Native Tool chain` in `Project Settings>Build` and testing again. Hopefully, it will give more info.

**Comment by theweavrs** [comment]
@Bond-009 Nothing changed. Let it hit the exception and also add this after `IReadOnlyList`:
``` csharp
var debugList = files.ToList();
```
I realized that `IReadOnlyList` is a COMObject meaning you can't see its value or what it contains. For that you must convert it into a `List` and then put a breakpoint there. After that, check the value of `debugList` and continue until you hits the exception.

**Pull request closed without merging**
