### PR TITLE
Started seperating BreadPlayer.Core from BreadPlayer.Views.UWP

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by theweavrs** [comment]
@Bond-009 Can you please convert BreadPlayer.Framework to PCL too? Would appreciate it very much. I am working on the Core, will push the changes after some testing.

**Comment by Bond-009** [comment]
I have a problem.
devenv_2016-12-30_15-29-54

**Comment by theweavrs** [comment]
@Bond-009 Still working on that...Multi-Threading in PCL is excruciating.

**Comment by Bond-009** [comment]
@theweavrs Is it ok if I merge with that error?

**Comment by theweavrs** [comment]
If all else is working, then of course. I will try and fix it after.

**Pull request merged**
